[package]
name = "snargs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-test-curves = { version = "0.4.2", feauture = [""] }

ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-std = "0.4.0"
itertools = "0.13.0"
rand = "0.8.5"
[dev-dependencies]
